const GET_WEATHER = 'GET_WEATHER';
const HANDLE_CLICK = 'HANDLE_CLICK';
const SET_SEARCH = 'SET_SEARCH';
const SET_VISIBLE = 'SET_VISIBLE';

export default {
  GET_WEATHER,
  HANDLE_CLICK,
  SET_SEARCH,
  SET_VISIBLE,
};