const GET_WEATHER = 'GET_WEATHER';
const HANDLE_CLICK = 'HANDLE_CLICK';
const SET_SEARCH = 'SET_SEARCH';
const SET_VISIBLE = 'SET_VISIBLE';
const SET_MAP = 'SET_MAP';
const GET_CURRENT_POSITION_FORECAST = 'GET_CURRENT_POSITION_FORECAST';
const LOADING_FORECAST = 'LOADING_FORECAST';
const SET_CHANGE = 'SET_CHANGE';
const SET_DAY_SELECTED = 'SET_DAY_SELECTED'

export default {
  GET_WEATHER,
  HANDLE_CLICK,
  SET_SEARCH,
  SET_VISIBLE,
  SET_MAP,
  GET_CURRENT_POSITION_FORECAST,
  LOADING_FORECAST,
  SET_CHANGE,
  SET_DAY_SELECTED
};